"""physics_v0 — the transparent urban runoff baseline.

Everything the UI shows in Phase 1 (risk colours, depth, "why is this zone red") comes from
these few lines. Phase 2 trains an XGBoost nowcast on labels generated by this same
generator, so the ML model learns the same monotonic relationships and the explanation
card can compare "model says" against "physics says".

Mass balance per zone, per tick (dt hours):

    inflow      = rain_mm_h × imperviousness           (rain that becomes surface runoff)
    surface_mm += (inflow − drainage_capacity) × dt    (never below zero)
    depth_cm    = surface_mm × concentration / 10      (runoff collects at the low point)

`concentration` is the geometric amplification between zone-average surface water and the
depth at the worst low point: an underpass collects a large catchment into a small basin
(×12); an ordinary street network collects roughly a third of the surface (×3).
A zone is "flooded" when the low-point depth reaches kerb height (15 cm).

Risk score (0–100) is a weighted sum of four normalised drivers plus two flat bonuses:

    0.25 × rain/40 mm/h  +  0.20 × cum3h/60 mm  +  0.25 × exceedance/25 mm/h  +  0.30 × depth/20 cm
    + 10 if the zone has an underpass and it is raining (≥ 5 mm/h)
    +  5 if the zone sits at or below 5 m elevation and it is raining

Bands used everywhere in the UI and rules: ≥ 40 yellow, ≥ 60 orange, ≥ 80 red.
"""

from __future__ import annotations

from dataclasses import dataclass, replace

RISK_SOURCE = "physics_v0"

CONCENTRATION_UNDERPASS = 12.0
CONCENTRATION_STREET = 3.0
FLOOD_DEPTH_CM = 15.0

# Normalisation scales ("what counts as extreme") and weights.
SCALE_RAIN_MM_H = 40.0
SCALE_CUM3H_MM = 60.0
SCALE_EXCEED_MM_H = 25.0
SCALE_DEPTH_CM = 20.0
W_RAIN, W_CUM, W_EXCEED, W_DEPTH = 0.25, 0.20, 0.25, 0.30
BONUS_UNDERPASS = 10.0
BONUS_LOW_ELEVATION = 5.0
LOW_ELEVATION_M = 5.0
RAINING_MM_H = 5.0

BAND_YELLOW, BAND_ORANGE, BAND_RED = 40.0, 60.0, 80.0


@dataclass(frozen=True)
class ZoneParams:
    zone_id: str
    imperviousness_pct: float
    drainage_capacity_mm_h: float
    elevation_m: float
    has_underpass: bool
    area_km2: float = 0.0
    population: int = 0
    criticality: int = 3

    @property
    def concentration(self) -> float:
        return CONCENTRATION_UNDERPASS if self.has_underpass else CONCENTRATION_STREET


@dataclass(frozen=True)
class ZoneState:
    surface_mm: float = 0.0

    def depth_cm(self, p: ZoneParams) -> float:
        return self.surface_mm * p.concentration / 10.0


def clamp01(x: float) -> float:
    return 0.0 if x < 0 else 1.0 if x > 1 else x


def inflow_mm_h(p: ZoneParams, rain_mm_h: float) -> float:
    return rain_mm_h * p.imperviousness_pct / 100.0


def exceedance_mm_h(p: ZoneParams, rain_mm_h: float) -> float:
    """Runoff arriving faster than the drains can take it."""
    return max(0.0, inflow_mm_h(p, rain_mm_h) - p.drainage_capacity_mm_h)


def step(p: ZoneParams, state: ZoneState, rain_mm_h: float, dt_h: float) -> ZoneState:
    surface = state.surface_mm + (inflow_mm_h(p, rain_mm_h) - p.drainage_capacity_mm_h) * dt_h
    return replace(state, surface_mm=max(0.0, surface))


def risk_score(p: ZoneParams, rain_mm_h: float, cum_3h_mm: float, depth_cm: float) -> float:
    parts = explain_risk(p, rain_mm_h, cum_3h_mm, depth_cm)
    return round(min(100.0, max(0.0, sum(v for _, v in parts))), 1)


def explain_risk(
    p: ZoneParams, rain_mm_h: float, cum_3h_mm: float, depth_cm: float
) -> list[tuple[str, float]]:
    """Ordered (driver, points) contributions — the 'WHY' shown on the zone card."""
    raining = rain_mm_h >= RAINING_MM_H
    return [
        ("rain_intensity", 100 * W_RAIN * clamp01(rain_mm_h / SCALE_RAIN_MM_H)),
        ("cumulative_3h", 100 * W_CUM * clamp01(cum_3h_mm / SCALE_CUM3H_MM)),
        ("drainage_exceedance", 100 * W_EXCEED * clamp01(exceedance_mm_h(p, rain_mm_h) / SCALE_EXCEED_MM_H)),
        ("standing_water", 100 * W_DEPTH * clamp01(depth_cm / SCALE_DEPTH_CM)),
        ("underpass", BONUS_UNDERPASS if (p.has_underpass and raining) else 0.0),
        ("low_elevation", BONUS_LOW_ELEVATION if (p.elevation_m <= LOW_ELEVATION_M and raining) else 0.0),
    ]


def band(risk: float) -> str:
    if risk >= BAND_RED:
        return "red"
    if risk >= BAND_ORANGE:
        return "orange"
    if risk >= BAND_YELLOW:
        return "yellow"
    return "green"


def describe() -> dict:
    """Machine-readable description of the formula, served by /api/meta for the UI tooltip."""
    return {
        "source": RISK_SOURCE,
        "flood_depth_cm": FLOOD_DEPTH_CM,
        "concentration": {"underpass": CONCENTRATION_UNDERPASS, "street": CONCENTRATION_STREET},
        "weights": {
            "rain_intensity": {"weight": W_RAIN, "scale": SCALE_RAIN_MM_H, "unit": "mm/h"},
            "cumulative_3h": {"weight": W_CUM, "scale": SCALE_CUM3H_MM, "unit": "mm"},
            "drainage_exceedance": {"weight": W_EXCEED, "scale": SCALE_EXCEED_MM_H, "unit": "mm/h"},
            "standing_water": {"weight": W_DEPTH, "scale": SCALE_DEPTH_CM, "unit": "cm"},
        },
        "bonuses": {"underpass": BONUS_UNDERPASS, "low_elevation": BONUS_LOW_ELEVATION},
        "bands": {"yellow": BAND_YELLOW, "orange": BAND_ORANGE, "red": BAND_RED},
        "formula": (
            "surface += (rain × imperviousness − drainage) × dt; "
            "depth = surface × concentration; "
            "risk = Σ weight × clamp(driver / scale) × 100 + bonuses"
        ),
    }
