"""ML models (Phase 2): zone flood-risk nowcast (XGBoost) + time-to-drain regressor.

Phase 1 serves the transparent physics_v0 baseline from `sadd.sim.physics`. Phase 2 trains
both models on labels generated by that baseline (`train.py`, < 60 s) and loads them once at
startup. GCP: both become BigQuery ML models over the same tables.
"""
